version: '3.6'
services:
  grpc-client:
    build:
      context: ../
      dockerfile: docker/php/Dockerfile
    container_name: grpc-client
    volumes:
      - ../grpc-client-php:/project
    networks:
      - dev_grpc_network
  grpc-server:
    build:
      context: ../
      dockerfile: docker/go/Dockerfile
    container_name: grpc-server
    networks:
      - dev_grpc_network

networks:
  dev_grpc_network:
      external: true

